export const countrieses = {
	AD: { countryName: "Andora", phcode: "376", key: "AD" },
	AE: { countryName: "Emiratos Árabes Unidos", phcode: "971", key: "AE" },
	AF: { countryName: "Afganistán", phcode: "93", key: "AF" },
	AG: { countryName: "Antigua y Barbuda", phcode: "1268", key: "AG" },
	AI: { countryName: "Anguilla", phcode: "1264", key: "AI" },
	AL: { countryName: "Albania", phcode: "355", key: "AL" },
	AM: { countryName: "Armenia", phcode: "374", key: "AM" },
	AN: { countryName: "Antillas Holandesas", phcode: "599", key: "AN" },
	AO: { countryName: "Angola", phcode: "244", key: "AO" },
	AQ: { countryName: "Antártida", phcode: "672", key: "AQ" },
	AR: { countryName: "Argentina", phcode: "54", key: "AR" },
	AS: { countryName: "Samoa, America", phcode: "1684", key: "AS" },
	AT: { countryName: "Austria", phcode: "43", key: "AT" },
	AU: { countryName: "Australia", phcode: "61", key: "AU" },
	AW: { countryName: "Aruba", phcode: "297", key: "AW" },
	AX: { countryName: "Islas Aland", phcode: "3581", key: "AX" },
	AZ: { countryName: "Azerbaijan", phcode: "994", key: "AZ" },
	BA: { countryName: "Bosnia-Herzegovina", phcode: "387", key: "BA" },
	BB: { countryName: "Barbados", phcode: "1246", key: "BB" },
	BD: { countryName: "Bangladesh", phcode: "880", key: "BD" },
	BE: { countryName: "Bélgica", phcode: "32", key: "BE" },
	BF: { countryName: "Burkina Faso", phcode: "226", key: "BF" },
	BG: { countryName: "Bulgaria", phcode: "359", key: "BG" },
	BH: { countryName: "Bahrein", phcode: "973", key: "BH" },
	BI: { countryName: "Barundi", phcode: "257", key: "BI" },
	BJ: { countryName: "Benin", phcode: "229", key: "BJ" },
	BL: { countryName: "San Bartolomé", phcode: "590", key: "BL" },
	BM: { countryName: "Bermuda", phcode: "1441", key: "BM" },
	BN: { countryName: "Brunei Darussalam", phcode: "673", key: "BN" },
	BO: { countryName: "Bolivia", phcode: "591", key: "BO" },
	BR: { countryName: "Brasil", phcode: "55", key: "BR" },
	BS: { countryName: "Bahamas", phcode: "1242", key: "BS" },
	BT: { countryName: "Bhután", phcode: "975", key: "BT" },
	BV: { countryName: "Isla Bouvet", phcode: "47", key: "BV" },
	BW: { countryName: "Botswana", phcode: "267", key: "BW" },
	BY: { countryName: "Belarús", phcode: "375", key: "BY" },
	BZ: { countryName: "Belice", phcode: "501", key: "BZ" },
	CC: { countryName: "Islas del Coco", phcode: "61", key: "CC" },
	CD: { countryName: "República Democrática del Congo", phcode: "242", key: "CD" },
	CF: { countryName: "República Centroafricana", phcode: "236", key: "CF" },
	CG: { countryName: "República del Congo", phcode: "242", key: "CG" },
	CH: { countryName: "Suiza", phcode: "41", key: "CH" },
	CI: { countryName: "Costa de Marfil", phcode: "225", key: "CI" },
	CK: { countryName: "Islas Cook", phcode: "682", key: "CK" },
	CL: { countryName: "Chile", phcode: "56", key: "CL" },
	CM: { countryName: "Camerún", phcode: "237", key: "CM" },
	CN: { countryName: "China", phcode: "86", key: "CN" },
	CO: { countryName: "Colombia", phcode: "57", key: "CO" },
	CR: { countryName: "Costa Rica", phcode: "506", key: "CR" },
	CU: { countryName: "Cuba", phcode: "53", key: "CU" },
	CV: { countryName: "Cape Verde", phcode: "238", key: "CV" },
	CX: { countryName: "Isla de Navidad", phcode: "61", key: "CX" },
	CY: { countryName: "Chipre", phcode: "357", key: "CY" },
	CZ: { countryName: "República Checa", phcode: "420", key: "CZ" },
	DE: { countryName: "Alemania", phcode: "49", key: "DE" },
	DJ: { countryName: "Djibouti", phcode: "253", key: "DJ" },
	DK: { countryName: "Dinamarca", phcode: "45", key: "DK" },
	DM: { countryName: "Dominica", phcode: "1767", key: "DM" },
	DO: { countryName: "República Dominicana", phcode: "1809", key: "DO" },
	DZ: { countryName: "Algeria", phcode: "213", key: "DZ" },
	EC: { countryName: "Ecuador", phcode: "593", key: "EC" },
	EE: { countryName: "Estonia", phcode: "372", key: "EE" },
	EG: { countryName: "Egypto", phcode: "20", key: "EG" },
	EH: { countryName: "Sahara Occidental", phcode: "212", key: "EH" },
	ER: { countryName: "Eritrea", phcode: "291", key: "ER" },
	ES: { countryName: "España", phcode: "34", key: "ES" },
	ET: { countryName: "Etiopía", phcode: "251", key: "ET" },
	FI: { countryName: "Finlandia", phcode: "358", key: "FI" },
	FJ: { countryName: "Fiji", phcode: "679", key: "FJ" },
	FK: { countryName: "Islas Malvinas", phcode: "500", key: "FK" },
	FM: { countryName: "Micronesia", phcode: "691", key: "FM" },
	FO: { countryName: "Islas Feroe", phcode: "298", key: "FO" },
	FR: { countryName: "Francia", phcode: "33", key: "FR" },
	GA: { countryName: "Gabón", phcode: "241", key: "GA" },
	GB: { countryName: "Reino Unido", phcode: "44", key: "GB" },
	GD: { countryName: "Granada", phcode: "1473", key: "GD" },
	GE: { countryName: "Georgia", phcode: "995", key: "GE" },
	GF: { countryName: "Guayana Francés", phcode: "594", key: "GF" },
	GG: { countryName: "Guernesey", phcode: "4414", key: "GG" },
	GH: { countryName: "Ghana", phcode: "233", key: "GH" },
	GI: { countryName: "Gibraltar", phcode: "350", key: "GI" },
	GL: { countryName: "Groenlandia", phcode: "299", key: "GL" },
	GM: { countryName: "Gambia", phcode: "220", key: "GM" },
	GN: { countryName: "Guinea", phcode: "224", key: "GN" },
	GP: { countryName: "Guadalupe", phcode: "590", key: "GP" },
	GQ: { countryName: "Guinea Ecuatorial", phcode: "240", key: "GQ" },
	GR: { countryName: "Grecia", phcode: "30", key: "GR" },
	GS: { countryName: "Islas Georgias del Sur y Sándwich del Sur", phcode: "500", key: "GS" },
	GT: { countryName: "Guatemala", phcode: "502", key: "GT" },
	GU: { countryName: "Guam", phcode: "1671", key: "GU" },
	GW: { countryName: "Guinea-Bissau", phcode: "245", key: "GW" },
	GY: { countryName: "Guyana", phcode: "592", key: "GY" },
	HK: { countryName: "Hong Kong", phcode: "852", key: "HK" },
	HM: { countryName: "Islas Heard Island y McDonald", phcode: "672", key: "HM" },
	HN: { countryName: "Honduras", phcode: "504", key: "HN" },
	HR: { countryName: "Croacia", phcode: "385", key: "HR" },
	HT: { countryName: "Haití", phcode: "509", key: "HT" },
	HU: { countryName: "Hungría", phcode: "36", key: "HU" },
	ID: { countryName: "Indonesia", phcode: "62", key: "ID" },
	IE: { countryName: "Irlanda", phcode: "353", key: "IE" },
	IM: { countryName: "Isla de Man", phcode: "44", key: "IM" },
	IN: { countryName: "India", phcode: "91", key: "IN" },
	IO: { countryName: "Territorio Británico del Océano Índico", phcode: "246", key: "IO" },
	IQ: { countryName: "Irak", phcode: "964", key: "IQ" },
	IR: { countryName: "Iran", phcode: "98", key: "IR" },
	IS: { countryName: "Islandia", phcode: "354", key: "IS" },
	IT: { countryName: "Italia", phcode: "39", key: "IT" },
	JE: { countryName: "Jersey", phcode: "4415", key: "JE" },
	JM: { countryName: "Jamaica", phcode: "1876", key: "JM" },
	JO: { countryName: "Jordán", phcode: "962", key: "JO" },
	JP: { countryName: "Japón", phcode: "81", key: "JP" },
	KE: { countryName: "Kenia", phcode: "254", key: "KE" },
	KG: { countryName: "Kirguistán", phcode: "996", key: "KG" },
	KH: { countryName: "Cambodia", phcode: "855", key: "KH" },
	KI: { countryName: "Kiribati", phcode: "686", key: "KI" },
	KM: { countryName: "Comoras", phcode: "269", key: "KM" },
	KN: { countryName: "San Cristobal y Nieves", phcode: "1758", key: "KN" },
	KP: { countryName: "Corea, República Popular Democrática", phcode: "850", key: "KP" },
	KR: { countryName: "Corea del Sur", phcode: "82", key: "KR" },
	KW: { countryName: "Kuwait", phcode: "965", key: "KW" },
	KY: { countryName: "Islas Caimán", phcode: "1345", key: "KY" },
	KZ: { countryName: "Kazajstán", phcode: "7", key: "KZ" },
	LA: { countryName: "Laos", phcode: "856", key: "LA" },
	LB: { countryName: "Líbano", phcode: "961", key: "LB" },
	LC: { countryName: "Santa Lucía", phcode: "1758", key: "LC" },
	LI: { countryName: "Liechtenstein", phcode: "423", key: "LI" },
	LK: { countryName: "Sri Lanka", phcode: "94", key: "LK" },
	LR: { countryName: "Liberia", phcode: "231", key: "LR" },
	LS: { countryName: "Lesoto", phcode: "266", key: "LS" },
	LT: { countryName: "Lituania", phcode: "370", key: "LT" },
	LU: { countryName: "Luxemburgo", phcode: "352", key: "LU" },
	LV: { countryName: "Letonia", phcode: "371", key: "LV" },
	LY: { countryName: "Libia", phcode: "218", key: "LY" },
	MA: { countryName: "Marruecos", phcode: "212", key: "MA" },
	MC: { countryName: "Mónaco", phcode: "377", key: "MC" },
	MD: { countryName: "Moldavia", phcode: "373", key: "MD" },
	ME: { countryName: "Montenegro", phcode: "382", key: "ME" },
	MF: { countryName: "San Martín", phcode: "590", key: "MF" },
	MG: { countryName: "Madagascar", phcode: "261", key: "MG" },
	MH: { countryName: "Islas Marshall", phcode: "692", key: "MH" },
	MK: { countryName: "Macedonia", phcode: "389", key: "MK" },
	ML: { countryName: "Mali", phcode: "223", key: "ML" },
	MM: { countryName: "Myanmar", phcode: "95", key: "MM" },
	MN: { countryName: "Mongolia", phcode: "976", key: "MN" },
	MO: { countryName: "Macao", phcode: "853", key: "MO" },
	MP: { countryName: "Islas Marianas del Norte", phcode: "1670", key: "MP" },
	MQ: { countryName: "Martinica", phcode: "596", key: "MQ" },
	MR: { countryName: "Mauritania", phcode: "222", key: "MR" },
	MS: { countryName: "Montserrat", phcode: "1664", key: "MS" },
	MT: { countryName: "Malta", phcode: "356", key: "MT" },
	MU: { countryName: "Mauricio", phcode: "230", key: "MU" },
	MV: { countryName: "Maldivas", phcode: "960", key: "MV" },
	MW: { countryName: "Malawi", phcode: "265", key: "MW" },
	MX: { countryName: "Méjico", phcode: "52", key: "MX" },
	MY: { countryName: "Malasia", phcode: "60", key: "MY" },
	MZ: { countryName: "Mozambique", phcode: "258", key: "MZ" },
	NA: { countryName: "Namibia", phcode: "264", key: "NA" },
	NC: { countryName: "Nueva Caledonia", phcode: "687", key: "NC" },
	NE: { countryName: "Níger", phcode: "227", key: "NE" },
	NF: { countryName: "Isla Norfolk", phcode: "672", key: "NF" },
	NG: { countryName: "Nigeria", phcode: "234", key: "NG" },
	NI: { countryName: "Nicaragua", phcode: "505", key: "NI" },
	NL: { countryName: "Países Bajos", phcode: "31", key: "NL" },
	NO: { countryName: "Noruega", phcode: "47", key: "NO" },
	NP: { countryName: "Nepal", phcode: "977", key: "NP" },
	NR: { countryName: "Nauru", phcode: "674", key: "NR" },
	NU: { countryName: "Niue", phcode: "683", key: "NU" },
	NZ: { countryName: "nueva Zelandia", phcode: "64", key: "NZ" },
	OM: { countryName: "Omán", phcode: "968", key: "OM" },
	PA: { countryName: "Panamá", phcode: "507", key: "PA" },
	PE: { countryName: "Perú", phcode: "51", key: "PE" },
	PF: { countryName: "Polinesia Francesa", phcode: "689", key: "PF" },
	PG: { countryName: "Papúa Nueva Guinea", phcode: "675", key: "PG" },
	PH: { countryName: "Filipinas", phcode: "63", key: "PH" },
	PK: { countryName: "Pakistán", phcode: "92", key: "PK" },
	PL: { countryName: "Polonia", phcode: "48", key: "PL" },
	PM: { countryName: "San Pedro y Miquelón", phcode: "508", key: "PM" },
	PN: { countryName: "Pitcairn", phcode: "64", key: "PN" },
	PS: { countryName: "Palestina", phcode: "970", key: "PS" },
	PT: { countryName: "Portugal", phcode: "351", key: "PT" },
	PW: { countryName: "Palau", phcode: "680", key: "PW" },
	PY: { countryName: "Paraguay", phcode: "595", key: "PY" },
	QA: { countryName: "Qatar", phcode: "974", key: "QA" },
	RE: { countryName: "Reunión", phcode: "262", key: "RE" },
	RO: { countryName: "Rumania", phcode: "40", key: "RO" },
	RS: { countryName: "Serbia", phcode: "381", key: "RS" },
	RU: { countryName: "Federación de Rusia", phcode: "7", key: "RU" },
	RW: { countryName: "Ruanda", phcode: "250", key: "RW" },
	SA: { countryName: "Arabia Saudita", phcode: "966", key: "SA" },
	SB: { countryName: "Islas Salomón", phcode: "677", key: "SB" },
	SC: { countryName: "Seychelles", phcode: "248", key: "SC" },
	SD: { countryName: "Sudán", phcode: "249", key: "SD" },
	SE: { countryName: "Suecia", phcode: "46", key: "SE" },
	SG: { countryName: "Singapur", phcode: "65", key: "SG" },
	SH: { countryName: "Santa Elena", phcode: "290", key: "SH" },
	SI: { countryName: "Eslovenia", phcode: "386", key: "SI" },
	SJ: { countryName: "Svalbard y Jan Mayen", phcode: "47", key: "SJ" },
	SK: { countryName: "Eslovaquia", phcode: "421", key: "SK" },
	SL: { countryName: "Sierra Leona", phcode: "232", key: "SL" },
	SM: { countryName: "San Marino", phcode: "378", key: "SM" },
	SN: { countryName: "Senegal", phcode: "221", key: "SN" },
	SO: { countryName: "Somalia", phcode: "252", key: "SO" },
	SR: { countryName: "Surinam", phcode: "597", key: "SR" },
	SS: { countryName: "Sudán del Sur", phcode: "211", key: "SS" },
	ST: { countryName: "Santo Tomé y Príncipe", phcode: "239", key: "ST" },
	SV: { countryName: "El Salvador", phcode: "503", key: "SV" },
	SY: { countryName: "República Árabe Siria", phcode: "963", key: "SY" },
	SZ: { countryName: "Swazilandia", phcode: "268", key: "SZ" },
	TC: { countryName: "Turks y Caicos", phcode: "1649", key: "TC" },
	TD: { countryName: "Chad", phcode: "235", key: "TD" },
	TF: { countryName: "Territorios Franceses del Sur", phcode: "689", key: "TF" },
	TG: { countryName: "Togo", phcode: "228", key: "TG" },
	TH: { countryName: "Tailandia", phcode: "66", key: "TH" },
	TJ: { countryName: "Tayikistán", phcode: "992", key: "TJ" },
	TK: { countryName: "Islas Tokelau", phcode: "690", key: "TK" },
	TL: { countryName: "Timor Oriental", phcode: "670", key: "TL" },
	TM: { countryName: "Turkmenistán", phcode: "993", key: "TM" },
	TN: { countryName: "Túnez", phcode: "216", key: "TN" },
	TO: { countryName: "Tonga", phcode: "676", key: "TO" },
	TR: { countryName: "Turquía", phcode: "90", key: "TR" },
	TT: { countryName: "Trinidad, Tobago", phcode: "1868", key: "TT" },
	TV: { countryName: "Tuvalu", phcode: "688", key: "TV" },
	TW: { countryName: "Taiwán", phcode: "886", key: "TW" },
	TZ: { countryName: "Tanzania", phcode: "255", key: "TZ" },
	UA: { countryName: "Ucrania", phcode: "380", key: "UA" },
	UG: { countryName: "Uganda", phcode: "256", key: "UG" },
	UM: { countryName: "Estados Unidos Islas Menores", phcode: "699", key: "UM" },
	UY: { countryName: "Uruguay", phcode: "598", key: "UY" },
	UZ: { countryName: "Uzbekistán", phcode: "998", key: "UZ" },
	VA: { countryName: "Ciudad del Vaticano", phcode: "379", key: "VA" },
	VC: { countryName: "San Vicente y las Granadinas", phcode: "1784", key: "VC" },
	VE: { countryName: "Venezuela", phcode: "58", key: "VE" },
	VG: { countryName: "Islas Vírgenes Británicas", phcode: "1284", key: "VG" },
	VI: { countryName: "Vírgenes estadounidenses Islas", phcode: "1340", key: "VI" },
	VN: { countryName: "Vietnam", phcode: "84", key: "VN" },
	VU: { countryName: "Vanuatu", phcode: "678", key: "VU" },
	WF: { countryName: "Wallis, Futuna", phcode: "681", key: "WF" },
	WS: { countryName: "Samoa", phcode: "685", key: "WS" },
	YE: { countryName: "Yemen", phcode: "967", key: "YE" },
	YT: { countryName: "Mayotte", phcode: "262", key: "YT" },
	ZA: { countryName: "Sudáfrica", phcode: "27", key: "ZA" },
	ZM: { countryName: "Zambia", phcode: "260", key: "ZM" },
	ZW: { countryName: "Zimbabwe", phcode: "263", key: "ZW" },
};