export const countriesar = {
	AD: { countryName: "أندورا", phcode: "376", key: "AD" },
	AE: { countryName: "الامارات العربية المتحدة", phcode: "971", key: "AE" },
	AF: { countryName: "أفغانستان", phcode: "93", key: "AF" },
	AG: { countryName: "أنتيجوا وبربودا", phcode: "1268", key: "AG" },
	AI: { countryName: "أنجويلا", phcode: "1264", key: "AI" },
	AL: { countryName: "ألبانيا", phcode: "355", key: "AL" },
	AM: { countryName: "أرمينيا", phcode: "374", key: "AM" },
	AN: { countryName: "جزر الأنتيل الهولندية", phcode: "599", key: "AN" },
	AO: { countryName: "أنجولا", phcode: "244", key: "AO" },
	AQ: { countryName: "القطب الجنوبي", phcode: "672", key: "AQ" },
	AR: { countryName: "الأرجنتين", phcode: "54", key: "AR" },
	AS: { countryName: "ساموا الأمريكية", phcode: "1684", key: "AS" },
	AT: { countryName: "النمسا", phcode: "43", key: "AT" },
	AU: { countryName: "أستراليا", phcode: "61", key: "AU" },
	AW: { countryName: "آروبا", phcode: "297", key: "AW" },
	AX: { countryName: "جزر أولان", phcode: "3581", key: "AX" },
	AZ: { countryName: "أذربيجان", phcode: "994", key: "AZ" },
	BA: { countryName: "البوسنة والهرسك", phcode: "387", key: "BA" },
	BB: { countryName: "بربادوس", phcode: "1246", key: "BB" },
	BD: { countryName: "بنجلاديش", phcode: "880", key: "BD" },
	BE: { countryName: "بلجيكا", phcode: "32", key: "BE" },
	BF: { countryName: "بوركينا فاسو", phcode: "226", key: "BF" },
	BG: { countryName: "بلغاريا", phcode: "359", key: "BG" },
	BH: { countryName: "البحرين", phcode: "973", key: "BH" },
	BI: { countryName: "بوروندي", phcode: "257", key: "BI" },
	BJ: { countryName: "بنين", phcode: "229", key: "BJ" },
	BL: { countryName: "سان بارتيلمي", phcode: "590", key: "BL" },
	BM: { countryName: "برمودا", phcode: "1441", key: "BM" },
	BN: { countryName: "بروناي", phcode: "673", key: "BN" },
	BO: { countryName: "بوليفيا", phcode: "591", key: "BO" },
	BR: { countryName: "البرازيل", phcode: "55", key: "BR" },
	BS: { countryName: "الباهاما", phcode: "1242", key: "BS" },
	BT: { countryName: "بوتان", phcode: "975", key: "BT" },
	BV: { countryName: "جزيرة بوفيه", phcode: "47", key: "BV" },
	BW: { countryName: "بتسوانا", phcode: "267", key: "BW" },
	BY: { countryName: "روسيا البيضاء", phcode: "375", key: "BY" },
	BZ: { countryName: "بليز", phcode: "501", key: "BZ" },
	CC: { countryName: "جزر كوكوس", phcode: "61", key: "CC" },
	CD: { countryName: "جمهورية كونغو الديمقراطية", phcode: "242", key: "CD" },
	CF: { countryName: "جمهورية افريقيا الوسطى", phcode: "236", key: "CF" },
	CG: { countryName: "الكونغو - برازافيل", phcode: "242", key: "CG" },
	CH: { countryName: "سويسرا", phcode: "41", key: "CH" },
	CI: { countryName: "ساحل العاج", phcode: "225", key: "CI" },
	CK: { countryName: "جزر كوك", phcode: "682", key: "CK" },
	CL: { countryName: "شيلي", phcode: "56", key: "CL" },
	CM: { countryName: "الكاميرون", phcode: "237", key: "CM" },
	CN: { countryName: "الصين", phcode: "86", key: "CN" },
	CO: { countryName: "كولومبيا", phcode: "57", key: "CO" },
	CR: { countryName: "كوستاريكا", phcode: "506", key: "CR" },
	CU: { countryName: "كوبا", phcode: "53", key: "CU" },
	CV: { countryName: "الرأس الأخضر", phcode: "238", key: "CV" },
	CX: { countryName: "جزيرة الكريسماس", phcode: "61", key: "CX" },
	CY: { countryName: "قبرص", phcode: "357", key: "CY" },
	CZ: { countryName: "جمهورية التشيك", phcode: "420", key: "CZ" },
	DE: { countryName: "ألمانيا", phcode: "49", key: "DE" },
	DJ: { countryName: "جيبوتي", phcode: "253", key: "DJ" },
	DK: { countryName: "الدانمرك", phcode: "45", key: "DK" },
	DM: { countryName: "دومينيكا", phcode: "1767", key: "DM" },
	DO: { countryName: "جمهورية الدومينيك", phcode: "1809", key: "DO" },
	DZ: { countryName: "الجزائر", phcode: "213", key: "DZ" },
	EC: { countryName: "الاكوادور", phcode: "593", key: "EC" },
	EE: { countryName: "استونيا", phcode: "372", key: "EE" },
	EG: { countryName: "مصر", phcode: "20", key: "EG" },
	EH: { countryName: "الصحراء الغربية", phcode: "212", key: "EH" },
	ER: { countryName: "اريتريا", phcode: "291", key: "ER" },
	ES: { countryName: "أسبانيا", phcode: "34", key: "ES" },
	ET: { countryName: "اثيوبيا", phcode: "251", key: "ET" },
	FI: { countryName: "فنلندا", phcode: "358", key: "FI" },
	FJ: { countryName: "فيجي", phcode: "679", key: "FJ" },
	FK: { countryName: "جزر فوكلاند", phcode: "500", key: "FK" },
	FM: { countryName: "ميكرونيسيا", phcode: "691", key: "FM" },
	FO: { countryName: "جزر فارو", phcode: "298", key: "FO" },
	FR: { countryName: "فرنسا", phcode: "33", key: "FR" },
	GA: { countryName: "الجابون", phcode: "241", key: "GA" },
	GB: { countryName: "المملكة المتحدة", phcode: "44", key: "GB" },
	GD: { countryName: "جرينادا", phcode: "1473", key: "GD" },
	GE: { countryName: "جورجيا", phcode: "995", key: "GE" },
	GF: { countryName: "غويانا الفرنسية", phcode: "594", key: "GF" },
	GG: { countryName: "غيرنسي", phcode: "4414", key: "GG" },
	GH: { countryName: "غانا", phcode: "233", key: "GH" },
	GI: { countryName: "جبل طارق", phcode: "350", key: "GI" },
	GL: { countryName: "غرينلاند", phcode: "299", key: "GL" },
	GM: { countryName: "غامبيا", phcode: "220", key: "GM" },
	GN: { countryName: "غينيا", phcode: "224", key: "GN" },
	GP: { countryName: "جوادلوب", phcode: "590", key: "GP" },
	GQ: { countryName: "غينيا الاستوائية", phcode: "240", key: "GQ" },
	GR: { countryName: "اليونان", phcode: "30", key: "GR" },
	GS: { countryName: "جورجيا الجنوبية وجزر ساندويتش الجنوبية", phcode: "500", key: "GS" },
	GT: { countryName: "غواتيمالا", phcode: "502", key: "GT" },
	GU: { countryName: "غوام", phcode: "1671", key: "GU" },
	GW: { countryName: "غينيا بيساو", phcode: "245", key: "GW" },
	GY: { countryName: "غيانا", phcode: "592", key: "GY" },
	HK: { countryName: "هونج كونج الصينية", phcode: "852", key: "HK" },
	HM: { countryName: "جزيرة هيرد وجزر ماكدونالد", phcode: "672", key: "HM" },
	HN: { countryName: "هندوراس", phcode: "504", key: "HN" },
	HR: { countryName: "كرواتيا", phcode: "385", key: "HR" },
	HT: { countryName: "هايتي", phcode: "509", key: "HT" },
	HU: { countryName: "المجر", phcode: "36", key: "HU" },
	ID: { countryName: "اندونيسيا", phcode: "62", key: "ID" },
	IE: { countryName: "أيرلندا", phcode: "353", key: "IE" },
	IM: { countryName: "جزيرة مان", phcode: "44", key: "IM" },
	IN: { countryName: "هند", phcode: "91", key: "IN" },
	IO: { countryName: "المحيط الهندي البريطاني", phcode: "246", key: "IO" },
	IQ: { countryName: "العراق", phcode: "964", key: "IQ" },
	IR: { countryName: "ايران", phcode: "98", key: "IR" },
	IS: { countryName: "أيسلندا", phcode: "354", key: "IS" },
	IT: { countryName: "ايطاليا", phcode: "39", key: "IT" },
	JE: { countryName: "جيرسي", phcode: "4415", key: "JE" },
	JM: { countryName: "جامايكا", phcode: "1876", key: "JM" },
	JO: { countryName: "الأردن", phcode: "962", key: "JO" },
	JP: { countryName: "اليابان", phcode: "81", key: "JP" },
	KE: { countryName: "كينيا", phcode: "254", key: "KE" },
	KG: { countryName: "قرغيزستان", phcode: "996", key: "KG" },
	KH: { countryName: "كمبوديا", phcode: "855", key: "KH" },
	KI: { countryName: "كيريباتي", phcode: "686", key: "KI" },
	KM: { countryName: "جزر القمر", phcode: "269", key: "KM" },
	KN: { countryName: "سانت كيتس ونيفيس", phcode: "1758", key: "KN" },
	KP: { countryName: "كوريا الشمالية", phcode: "850", key: "KP" },
	KR: { countryName: "كوريا الجنوبية", phcode: "82", key: "KR" },
	KW: { countryName: "الكويت", phcode: "965", key: "KW" },
	KY: { countryName: "جزر الكايمن", phcode: "1345", key: "KY" },
	KZ: { countryName: "كازاخستان", phcode: "7", key: "KZ" },
	LA: { countryName: "لاوس", phcode: "856", key: "LA" },
	LB: { countryName: "لبنان", phcode: "961", key: "LB" },
	LC: { countryName: "سانت لوسيا", phcode: "1758", key: "LC" },
	LI: { countryName: "ليختنشتاين", phcode: "423", key: "LI" },
	LK: { countryName: "سريلانكا", phcode: "94", key: "LK" },
	LR: { countryName: "ليبيريا", phcode: "231", key: "LR" },
	LS: { countryName: "ليسوتو", phcode: "266", key: "LS" },
	LT: { countryName: "ليتوانيا", phcode: "370", key: "LT" },
	LU: { countryName: "لوكسمبورغ", phcode: "352", key: "LU" },
	LV: { countryName: "لاتفيا", phcode: "371", key: "LV" },
	LY: { countryName: "ليبيا", phcode: "218", key: "LY" },
	MA: { countryName: "المغرب", phcode: "212", key: "MA" },
	MC: { countryName: "موناكو", phcode: "377", key: "MC" },
	MD: { countryName: "مولدافيا", phcode: "373", key: "MD" },
	ME: { countryName: "الجبل الأسود", phcode: "382", key: "ME" },
	MF: { countryName: "سانت مارتين", phcode: "590", key: "MF" },
	MG: { countryName: "مدغشقر", phcode: "261", key: "MG" },
	MH: { countryName: "جزر المارشال", phcode: "692", key: "MH" },
	MK: { countryName: "مقدونيا", phcode: "389", key: "MK" },
	ML: { countryName: "مالي", phcode: "223", key: "ML" },
	MM: { countryName: "ميانمار", phcode: "95", key: "MM" },
	MN: { countryName: "منغوليا", phcode: "976", key: "MN" },
	MO: { countryName: "ماكاو الصينية", phcode: "853", key: "MO" },
	MP: { countryName: "جزر ماريانا الشمالية", phcode: "1670", key: "MP" },
	MQ: { countryName: "مارتينيك", phcode: "596", key: "MQ" },
	MR: { countryName: "موريتانيا", phcode: "222", key: "MR" },
	MS: { countryName: "مونتسرات", phcode: "1664", key: "MS" },
	MT: { countryName: "مالطا", phcode: "356", key: "MT" },
	MU: { countryName: "موريشيوس", phcode: "230", key: "MU" },
	MV: { countryName: "جزر الملديف", phcode: "960", key: "MV" },
	MW: { countryName: "ملاوي", phcode: "265", key: "MW" },
	MX: { countryName: "المكسيك", phcode: "52", key: "MX" },
	MY: { countryName: "ماليزيا", phcode: "60", key: "MY" },
	MZ: { countryName: "موزمبيق", phcode: "258", key: "MZ" },
	NA: { countryName: "ناميبيا", phcode: "264", key: "NA" },
	NC: { countryName: "كاليدونيا الجديدة", phcode: "687", key: "NC" },
	NE: { countryName: "النيجر", phcode: "227", key: "NE" },
	NF: { countryName: "جزيرة نورفوك", phcode: "672", key: "NF" },
	NG: { countryName: "نيجيريا", phcode: "234", key: "NG" },
	NI: { countryName: "نيكاراجوا", phcode: "505", key: "NI" },
	NL: { countryName: "هولندا", phcode: "31", key: "NL" },
	NO: { countryName: "النرويج", phcode: "47", key: "NO" },
	NP: { countryName: "نيبال", phcode: "977", key: "NP" },
	NR: { countryName: "ناورو", phcode: "674", key: "NR" },
	NU: { countryName: "نيوي", phcode: "683", key: "NU" },
	NZ: { countryName: "نيوزيلاندا", phcode: "64", key: "NZ" },
	OM: { countryName: "عمان", phcode: "968", key: "OM" },
	PA: { countryName: "بنما", phcode: "507", key: "PA" },
	PE: { countryName: "بيرو", phcode: "51", key: "PE" },
	PF: { countryName: "بولينيزيا الفرنسية", phcode: "689", key: "PF" },
	PG: { countryName: "بابوا غينيا الجديدة", phcode: "675", key: "PG" },
	PH: { countryName: "الفيلبين", phcode: "63", key: "PH" },
	PK: { countryName: "باكستان", phcode: "92", key: "PK" },
	PL: { countryName: "بولندا", phcode: "48", key: "PL" },
	PM: { countryName: "سانت بيير وميكولون", phcode: "508", key: "PM" },
	PN: { countryName: "جزر بيتكيرن", phcode: "64", key: "PN" },
	PS: { countryName: "فلسطين", phcode: "970", key: "PS" },
	PT: { countryName: "البرتغال", phcode: "351", key: "PT" },
	PW: { countryName: "بالاو", phcode: "680", key: "PW" },
	PY: { countryName: "باراغواي", phcode: "595", key: "PY" },
	QA: { countryName: "قطر", phcode: "974", key: "QA" },
	RE: { countryName: "روينيون", phcode: "262", key: "RE" },
	RO: { countryName: "رومانيا", phcode: "40", key: "RO" },
	RS: { countryName: "صربيا", phcode: "381", key: "RS" },
	RU: { countryName: "روسيا", phcode: "7", key: "RU" },
	RW: { countryName: "رواندا", phcode: "250", key: "RW" },
	SA: { countryName: "المملكة العربية السعودية", phcode: "966", key: "SA" },
	SB: { countryName: "جزر سليمان", phcode: "677", key: "SB" },
	SC: { countryName: "سيشل", phcode: "248", key: "SC" },
	SD: { countryName: "السودان", phcode: "249", key: "SD" },
	SE: { countryName: "السويد", phcode: "46", key: "SE" },
	SG: { countryName: "سنغافورة", phcode: "65", key: "SG" },
	SH: { countryName: "سانت هيلينا", phcode: "290", key: "SH" },
	SI: { countryName: "سلوفينيا", phcode: "386", key: "SI" },
	SJ: { countryName: "سفالبارد وجان مايان", phcode: "47", key: "SJ" },
	SK: { countryName: "سلوفاكيا", phcode: "421", key: "SK" },
	SL: { countryName: "سيراليون", phcode: "232", key: "SL" },
	SM: { countryName: "سان مارينو", phcode: "378", key: "SM" },
	SN: { countryName: "السنغال", phcode: "221", key: "SN" },
	SO: { countryName: "الصومال", phcode: "252", key: "SO" },
	SR: { countryName: "سورينام", phcode: "597", key: "SR" },
	SS: { countryName: "جنوب السودان", phcode: "211", key: "SS" },
	ST: { countryName: "ساو تومي وبرينسيبي", phcode: "239", key: "ST" },
	SV: { countryName: "السلفادور", phcode: "503", key: "SV" },
	SY: { countryName: "الجمهورية العربية السورية", phcode: "963", key: "SY" },
	SZ: { countryName: "سوازيلاند", phcode: "268", key: "SZ" },
	TC: { countryName: "جزر توركس وكايكوس", phcode: "1649", key: "TC" },
	TD: { countryName: "تشاد", phcode: "235", key: "TD" },
	TF: { countryName: "المقاطعات الجنوبية الفرنسية", phcode: "689", key: "TF" },
	TG: { countryName: "توجو", phcode: "228", key: "TG" },
	TH: { countryName: "تايلند", phcode: "66", key: "TH" },
	TJ: { countryName: "طاجكستان", phcode: "992", key: "TJ" },
	TK: { countryName: "توكيلاو", phcode: "690", key: "TK" },
	TL: { countryName: "تيمور الشرقية", phcode: "670", key: "TL" },
	TM: { countryName: "تركمانستان", phcode: "993", key: "TM" },
	TN: { countryName: "تونس", phcode: "216", key: "TN" },
	TO: { countryName: "تونجا", phcode: "676", key: "TO" },
	TR: { countryName: "تركيا", phcode: "90", key: "TR" },
	TT: { countryName: "ترينيداد وتوباغو", phcode: "1868", key: "TT" },
	TV: { countryName: "توفالو", phcode: "688", key: "TV" },
	TW: { countryName: "تايوان", phcode: "886", key: "TW" },
	TZ: { countryName: "تانزانيا", phcode: "255", key: "TZ" },
	UA: { countryName: "أوكرانيا", phcode: "380", key: "UA" },
	UG: { countryName: "أوغندا", phcode: "256", key: "UG" },
	UM: { countryName: "جزر الولايات المتحدة البعيدة الصغيرة", phcode: "699", key: "UM" },
	UY: { countryName: "أورغواي", phcode: "598", key: "UY" },
	UZ: { countryName: "أوزبكستان", phcode: "998", key: "UZ" },
	VA: { countryName: "الفاتيكان", phcode: "379", key: "VA" },
	VC: { countryName: "سانت فنسنت وغرنادين", phcode: "1784", key: "VC" },
	VE: { countryName: "فنزويلا", phcode: "58", key: "VE" },
	VG: { countryName: "جزر فرجين البريطانية", phcode: "1284", key: "VG" },
	VI: { countryName: "جزر فرجين الأمريكية", phcode: "1340", key: "VI" },
	VN: { countryName: "فيتنام", phcode: "84", key: "VN" },
	VU: { countryName: "فانواتو", phcode: "678", key: "VU" },
	WF: { countryName: "جزر والس وفوتونا", phcode: "681", key: "WF" },
	WS: { countryName: "ساموا", phcode: "685", key: "WS" },
	YE: { countryName: "اليمن", phcode: "967", key: "YE" },
	YT: { countryName: "مايوت", phcode: "262", key: "YT" },
	ZA: { countryName: "جمهورية جنوب افريقيا", phcode: "27", key: "ZA" },
	ZM: { countryName: "زامبيا", phcode: "260", key: "ZM" },
	ZW: { countryName: "زيمبابوي", phcode: "263", key: "ZW" },
};