export const countriesuk = {
    AD: { phcode: "376", countryName: "Андорра", key: "AD" },
    AE: { phcode: "971", countryName: "Об'єднані Арабські Емірати", key: "AE" },
    AF: { phcode: "93", countryName: "Афганістан", key: "AF" },
    AG: { phcode: "1268", countryName: "Антигуа і Барбуда", key: "AG" },
    AI: { phcode: "1264", countryName: "Ангілья", key: "AI" },
    AL: { phcode: "355", countryName: "Албанія", key: "AL" },
    AM: { phcode: "374", countryName: "Вірменія", key: "AM" },
    AN: { phcode: "599", countryName: "Антильські острови", key: "AN" },
    AO: { phcode: "244", countryName: "Ангола", key: "AO" },
    AQ: { phcode: "672", countryName: "Антарктика", key: "AQ" },
    AR: { phcode: "54", countryName: "Аргентина", key: "AR" },
    AS: { phcode: "1684", countryName: "Американські Самоа", key: "AS" },
    AT: { phcode: "43", countryName: "Австрія", key: "AT" },
    AU: { phcode: "61", countryName: "Австралія", key: "AU" },
    AW: { phcode: "297", countryName: "Аруба", key: "AW" },
    AX: { phcode: "3581", countryName: "Аландські острови", key: "AX" },
    AZ: { phcode: "994", countryName: "Азербайджан", key: "AZ" },
    BA: { phcode: "387", countryName: "Боснія і Герцеговина", key: "BA" },
    BB: { phcode: "одна тисяча двісті сорок шість", countryName: "Барбадос", key: "BB" },
    BD: { phcode: "880", countryName: "Бангладеш", key: "BD" },
    BE: { phcode: "32", countryName: "Бельгія", key: "BE" },
    BF: { phcode: "226", countryName: "Буркіна Фасо", key: "BF" },
    BG: { phcode: "359", countryName: "Болгарія", key: "BG" },
    BH: { phcode: "973", countryName: "Бахрейн", key: "BH" },
    BI: { phcode: "257", countryName: "Бурунді", key: "BI" },
    BJ: { phcode: "229", countryName: "Бенін", key: "BJ" },
    BL: { phcode: "590", countryName: "Санкт-Бартельмі", key: "BL" },
    BM: { phcode: "1441", countryName: "Бермуди", key: "BM" },
    BN: { phcode: "673", countryName: "Бруней-Даруссалам", key: "BN" },
    BO: { phcode: "591", countryName: "Болівія", key: "BO" },
    BR: { phcode: "55", countryName: "Бразилія", key: "BR" },
    BS: { phcode: "одна тисяча двісті сорок дві", countryName: "Багами", key: "BS" },
    BT: { phcode: "975", countryName: "Бутан", key: "BT" },
    BV: { phcode: "47", countryName: "Буве", key: "BV" },
    BW: { phcode: "267", countryName: "Ботсвана", key: "BW" },
    BY: { phcode: "375", countryName: "Білорусь", key: "BY" },
    BZ: { phcode: "501", countryName: "Беліз", key: "BZ" },
    CA: { phcode: "1", countryName: "Канада", key: 'CA' },
    CC: { phcode: "61", countryName: "Кокосові острови (Кілінг)", key: "CC" },
    CD: { phcode: "242", countryName: "Демократична Республіка Конго", key: "CD" },
    CF: { phcode: "236", countryName: "Центрально-Африканська Республіка", key: "CF" },
    CG: { phcode: "242", countryName: "Конго", key: "CG" },
    CH: { phcode: "41", countryName: "Швейцарія", key: "CH" },
    CI: { phcode: "225", countryName: "Кот-д`Івуар", key: "CI" },
    CK: { phcode: "682", countryName: "Острови Кука", key: "CK" },
    CL: { phcode: "56", countryName: "Чилі", key: "CL" },
    CM: { phcode: "237", countryName: "Камерун", key: "CM" },
    CN: { phcode: "86", countryName: "Китай", key: "CN" },
    CO: { phcode: "57", countryName: "Колумбія", key: "CO" },
    CR: { phcode: "506", countryName: "Коста-Ріка", key: "CR" },
    CU: { phcode: "53", countryName: "Куба", key: "CU" },
    CV: { phcode: "238", countryName: "Кабо-Верде", key: "CV" },
    CX: { phcode: "61", countryName: "Острів Різдва", key: "CX" },
    CY: { phcode: "357", countryName: "Кіпр", key: "CY" },
    CZ: { phcode: "420", countryName: "Чеська Республіка", key: "CZ" },
    DE: { phcode: "49", countryName: "Німеччина", key: "DE" },
    DJ: { phcode: "253", countryName: "Джібуті", key: "DJ" },
    DK: { phcode: "45", countryName: "Данія", key: "DK" },
    DM: { phcode: "1767", countryName: "Домінікана", key: "DM" },
    DO: { phcode: "1809", countryName: "Домініканська Республіка", key: "DO" },
    DZ: { phcode: "213", countryName: "Алжир", key: "DZ" },
    EC: { phcode: "593", countryName: "Еквадор", key: "EC" },
    EE: { phcode: "372", countryName: "Естонія", key: "EE" },
    EG: { phcode: "20", countryName: "Єгипет", key: "EG" },
    EH: { phcode: "212", countryName: "Західна Сахара", key: "EH" },
    ER: { phcode: "291", countryName: "Еритрея", key: "ER" },
    ES: { phcode: "34", countryName: "Іспанія", key: "ES" },
    ET: { phcode: "251", countryName: "Ефіопія", key: "ET" },
    FI: { phcode: "358", countryName: "Фінляндія", key: "FI" },
    FJ: { phcode: "679", countryName: "Фіджі", key: "FJ" },
    FK: { phcode: "500", countryName: "Фолклендські (Мальвінські) острови", key: "FK" },
    FM: { phcode: "691", countryName: "Мікронезія", key: "FM" },
    FO: { phcode: "298", countryName: "Фарерські острови", key: "FO" },
    FR: { phcode: "33", countryName: "Франція", key: "FR" },
    GA: { phcode: "241", countryName: "Габон", key: "GA" },
    GB: { phcode: "44", countryName: "Великобританія", key: "GB" },
    GD: { phcode: "1473", countryName: "Гренада", key: "GD" },
    GE: { phcode: "995", countryName: "Грузія", key: "GE" },
    GF: { phcode: "594", countryName: "Французька Гвіана", key: "GF" },
    GG: { phcode: "4414", countryName: "Гернсі", key: "GG" },
    GH: { phcode: "233", countryName: "Гана", key: "GH" },
    GI: { phcode: "350", countryName: "Гібралтар", key: "GI" },
    GL: { phcode: "299", countryName: "Гренландія", key: "GL" },
    GM: { phcode: "220", countryName: "Гамбія", key: "GM" },
    GN: { phcode: "224", countryName: "Гвінея", key: "GN" },
    GP: { phcode: "590", countryName: "Гваделупі", key: "GP" },
    GQ: { phcode: "240", countryName: "Екваторіальна Гвінея", key: "GQ" },
    GR: { phcode: "30", countryName: "Греція", key: "GR" },
    GS: { phcode: "500", countryName: "Південна Джорджія та Південні Сандвічеві Острови", key: "GS" },
    GT: { phcode: "502", countryName: "Гватемалі", key: "GT" },
    GU: { phcode: "тисячу шістсот сімдесят один", countryName: "Гуам", key: "GU" },
    GW: { phcode: "245", countryName: "Гвінея-Біссау", key: "GW" },
    GY: { phcode: "592", countryName: "Гайана", key: "GY" },
    HK: { phcode: "852", countryName: "Гонконг", key: "HK" },
    HM: { phcode: "672", countryName: "Острови Херд і Макдональд", key: "HM" },
    HN: { phcode: "504", countryName: "Гондурас", key: "HN" },
    HR: { phcode: "385", countryName: "Хорватія", key: "HR" },
    HT: { phcode: "509", countryName: "Гаїті", key: "HT" },
    HU: { phcode: "36", countryName: "Угорщина", key: "HU" },
    ID: { phcode: "62", countryName: "Індонезія", key: "ID" },
    IE: { phcode: "353", countryName: "Ірландія", key: "IE" },
    IL: { phcode: "972", countryName: "Ізраїль", key: 'IL' },
    IM: { phcode: "44", countryName: "Острів Мен", key: "IM" },
    IN: { phcode: "91", countryName: "Індія", key: "IN" },
    IO: { phcode: "246", countryName: "Британська територія в Індійському океані", key: "IO" },
    IQ: { phcode: "964", countryName: "Ірак", key: "IQ" },
    IR: { phcode: "98", countryName: "Іран", key: "IR" },
    IS: { phcode: "354", countryName: "Ісландія", key: "IS" },
    IT: { phcode: "39", countryName: "Італія", key: "IT" },
    JE: { phcode: "4415", countryName: "Джерсі", key: "JE" },
    JM: { phcode: "1876", countryName: "Ямайка", key: "JM" },
    JO: { phcode: "962", countryName: "Йорданія", key: "JO" },
    JP: { phcode: "81", countryName: "Японія", key: "JP" },
    KE: { phcode: "254", countryName: "Кенія", key: "KE" },
    KG: { phcode: "996", countryName: "Киргизстан", key: "KG" },
    KH: { phcode: "855", countryName: "Камбоджа", key: "KH" },
    KI: { phcode: "686", countryName: "Кірібаті", key: "KI" },
    KM: { phcode: "269", countryName: "Коморські Острови", key: "KM" },
    KN: { phcode: "1758", countryName: "Сент-Кітс і Невіс", key: "KN" },
    KP: { phcode: "850", countryName: "Північна Корея", key: "KP" },
    KR: { phcode: "82", countryName: "Південна Корея", key: "KR" },
    KV: { phcode: "383", countryName: "Косово", key: 'KV' },
    KW: { phcode: "965", countryName: "Кувейт", key: "KW" },
    KY: { phcode: "тисячі триста сорок п'ять", countryName: "Кайманові острови", key: "KY" },
    KZ: { phcode: "7", countryName: "Казахстан", key: "KZ" },
    LA: { phcode: "856", countryName: "Лаос", key: "LA" },
    LB: { phcode: "961", countryName: "Ліван", key: "LB" },
    LC: { phcode: "1758", countryName: "Сент-Люсії", key: "LC" },
    LI: { phcode: "423", countryName: "Ліхтенштейн", key: "LI" },
    LK: { phcode: "94", countryName: "Шрі-Ланка", key: "LK" },
    LR: { phcode: "231", countryName: "Ліберія", key: "LR" },
    LS: { phcode: "266", countryName: "Лесото", key: "LS" },
    LT: { phcode: "370", countryName: "Литва", key: "LT" },
    LU: { phcode: "352", countryName: "Люксембург", key: "LU" },
    LV: { phcode: "371", countryName: "Латвія", key: "LV" },
    LY: { phcode: "218", countryName: "Лівія", key: "LY" },
    MA: { phcode: "212", countryName: "Морокко", key: "MA" },
    MC: { phcode: "377", countryName: "Монако", key: "MC" },
    MD: { phcode: "373", countryName: "Молдова", key: "MD" },
    ME: { phcode: "382", countryName: "Чорногорія", key: "ME" },
    MF: { phcode: "590", countryName: "Святий Мартин", key: "MF" },
    MG: { phcode: "261", countryName: "Мадагаскар", key: "MG" },
    MH: { phcode: "692", countryName: "Маршаллові Острови", key: "MH" },
    MK: { phcode: "389", countryName: "Македонія", key: "MK" },
    ML: { phcode: "223", countryName: "Малі", key: "ML" },
    MM: { phcode: "95", countryName: "М'янма", key: "MM" },
    MN: { phcode: "976", countryName: "Монголія", key: "MN" },
    MO: { phcode: "853", countryName: "Макао", key: "MO" },
    MP: { phcode: "1670", countryName: "Північні Маріанські острови", key: "MP" },
    MQ: { phcode: "596", countryName: "Мартініка", key: "MQ" },
    MR: { phcode: "222", countryName: "Мавританія", key: "MR" },
    MS: { phcode: "1664", countryName: "Монтсеррат", key: "MS" },
    MT: { phcode: "356", countryName: "Мальта", key: "MT" },
    MU: { phcode: "230", countryName: "Острів Маврикій", key: "MU" },
    MV: { phcode: "960", countryName: "Мальдіви", key: "MV" },
    MW: { phcode: "265", countryName: "Малаві", key: "MW" },
    MX: { phcode: "52", countryName: "Мексика", key: "MX" },
    MY: { phcode: "60", countryName: "Малайзія", key: "MY" },
    MZ: { phcode: "258", countryName: "Мозамбік", key: "MZ" },
    NA: { phcode: "264", countryName: "Намібія", key: "NA" },
    NC: { phcode: "687", countryName: "Нова Каледонія", key: "NC" },
    NE: { phcode: "227", countryName: "Нігер", key: "NE" },
    NF: { phcode: "672", countryName: "Острів Норфолк", key: "NF" },
    NG: { phcode: "234", countryName: "Нігерія", key: "NG" },
    NI: { phcode: "505", countryName: "Нікарагуа", key: "NI" },
    NL: { phcode: "31", countryName: "Нідерланди", key: "NL" },
    NO: { phcode: "47", countryName: "Норвегія", key: "NO" },
    NP: { phcode: "977", countryName: "Непал", key: "NP" },
    NR: { phcode: "674", countryName: "Науру", key: "NR" },
    NU: { phcode: "683", countryName: "Ніуе", key: "NU" },
    NZ: { phcode: "64", countryName: "Нова Зеландія", key: "NZ" },
    OM: { phcode: "968", countryName: "Оман", key: "OM" },
    PA: { phcode: "507", countryName: "Панама", key: "PA" },
    PE: { phcode: "51", countryName: "Перу", key: "PE" },
    PF: { phcode: "689", countryName: "Французька Полінезія", key: "PF" },
    PG: { phcode: "675", countryName: "Папуа Нова Гвінея", key: "PG" },
    PH: { phcode: "63", countryName: "Філіппіни", key: "PH" },
    PK: { phcode: "92", countryName: "Пакистан", key: "PK" },
    PL: { phcode: "48", countryName: "Польща", key: "PL" },
    PM: { phcode: "508", countryName: "Сен-П'єр і Мікелон", key: "PM" },
    PN: { phcode: "64", countryName: "Піткерн", key: "PN" },
    PR: { phcode: "тисяча сімсот вісімдесят сім", countryName: "Пуерто-Ріко", key: "PR" },
    PS: { phcode: "970", countryName: "Палестина", key: "PS" },
    PT: { phcode: "351", countryName: "Португалія", key: "PT" },
    PW: { phcode: "680", countryName: "Палау", key: "PW" },
    PY: { phcode: "595", countryName: "Парагвай", key: "PY" },
    QA: { phcode: "974", countryName: "Катар", key: "QA" },
    RE: { phcode: "262", countryName: "Реюньон", key: "RE" },
    RO: { phcode: "40", countryName: "Румунія", key: "RO" },
    RS: { phcode: "381", countryName: "Сербія", key: "RS" },
    RU: { phcode: "7", countryName: "Російська Федерація", key: "RU" },
    RW: { phcode: "250", countryName: "Руанда", key: "RW" },
    SA: { phcode: "966", countryName: "Саудівська Аравія", key: "SA" },
    SB: { phcode: "677", countryName: "Соломонові острови", key: "SB" },
    SC: { phcode: "248", countryName: "Сейшельські острови", key: "SC" },
    SD: { phcode: "249", countryName: "Судан", key: "SD" },
    SE: { phcode: "46", countryName: "Швеція", key: "SE" },
    SG: { phcode: "65", countryName: "Сінгапур", key: "SG" },
    SH: { phcode: "290", countryName: "Свята Єлена", key: "SH" },
    SI: { phcode: "386", countryName: "Словенія", key: "SI" },
    SJ: { phcode: "47", countryName: "Свалбард і Жан Маєн", key: "SJ" },
    SK: { phcode: "421", countryName: "Словаччина", key: "SK" },
    SL: { phcode: "232", countryName: "Сьєрра Ліон", key: "SL" },
    SM: { phcode: "378", countryName: "Сан-Марино", key: "SM" },
    SN: { phcode: "221", countryName: "Сенегал", key: "SN" },
    SO: { phcode: "252", countryName: "Сомалі", key: "SO" },
    SR: { phcode: "597", countryName: "Суринам", key: "SR" },
    SS: { phcode: "211", countryName: "Південний Судан", key: "SS" },
    ST: { phcode: "239", countryName: "Сан-Томе і Прінсіпі", key: "ST" },
    SV: { phcode: "503", countryName: "Сальвадор", key: "SV" },
    SY: { phcode: "963", countryName: "Сирія", key: "SY" },
    SZ: { phcode: "268", countryName: "Свазіленд", key: "SZ" },
    TC: { phcode: "1649", countryName: "Теркс і Кайкос", key: "TC" },
    TD: { phcode: "235", countryName: "Чад", key: "TD" },
    TF: { phcode: "689", countryName: "Французькі Південні території", key: "TF" },
    TG: { phcode: "228", countryName: "Того", key: "TG" },
    TH: { phcode: "66", countryName: "Таїланд", key: "TH" },
    TJ: { phcode: "992", countryName: "Таджикистан", key: "TJ" },
    TK: { phcode: "690", countryName: "Токелау", key: "TK" },
    TL: { phcode: "670", countryName: "Тимор-Лешті", key: "TL" },
    TM: { phcode: "993", countryName: "Туркменістан", key: "TM" },
    TN: { phcode: "216", countryName: "Туніс", key: "TN" },
    TO: { phcode: "676", countryName: "Тонга", key: "TO" },
    TP: { phcode: "670", countryName: "Східний Тимор", key: 'TP' },
    TR: { phcode: "90", countryName: "Туреччина", key: "TR" },
    TT: { phcode: "1868", countryName: "Тринідад і Тобаго", key: "TT" },
    TV: { phcode: "688", countryName: "Тувалу", key: "TV" },
    TW: { phcode: "886", countryName: "Тайвань", key: "TW" },
    TZ: { phcode: "255", countryName: "Танзанія", key: "TZ" },
    UA: { phcode: "380", countryName: "Україна", key: "UA" },
    UG: { phcode: "256", countryName: "Уганда", key: "UG" },
    UM: { phcode: "699", countryName: "США Зовнішні малі острови", key: "UM" },
    US: { phcode: "1", countryName: "США", key: "US" },
    UY: { phcode: "598", countryName: "Уругвай", key: "UY" },
    UZ: { phcode: "998", countryName: "Узбекистан", key: "UZ" },
    VA: { phcode: "379", countryName: "Ватикан", key: "VA" },
    VC: { phcode: "1784", countryName: "Сент-Вінсент і Гренадіни", key: "VC" },
    VE: { phcode: "58", countryName: "Венесуела", key: "VE" },
    VG: { phcode: "+1284", countryName: "Британські Віргінські острови", key: "VG" },
    VI: { phcode: "1340", countryName: "Американські Віргінські острови", key: "VI" },
    VN: { phcode: "84", countryName: "В'єтнам", key: "VN" },
    VU: { phcode: "678", countryName: "Вануату", key: "VU" },
    WF: { phcode: "681", countryName: "Уолліс і Футуна", key: "WF" },
    WS: { phcode: "685", countryName: "Самоа", key: "WS" },
    YE: { phcode: "967", countryName: "Ємен", key: "YE" },
    YT: { phcode: "262", countryName: "Майотта", key: "YT" },
    ZA: { phcode: "27", countryName: "Південна Африка", key: "ZA" },
    ZM: { phcode: "260", countryName: "Замбія", key: "ZM" },
    ZW: { phcode: "263", countryName: "Зімбабве", key: "ZW" }
};