export const countriesru = {
	AD: { phcode: "376", countryName: "Андорра", key: "AD" },
	AE: { phcode: "971", countryName: "Объединенные Арабские Эмираты", key: "AE" },
	AF: { phcode: "93", countryName: "Афганистан", key: "AF" },
	AG: { phcode: "1268", countryName: "Антигуа и Барбуда", key: "AG" },
	AI: { phcode: "1264", countryName: "Ангилья", key: "AI" },
	AL: { phcode: "355", countryName: "Албания", key: "AL" },
	AM: { phcode: "374", countryName: "Армения", key: "AM" },
	AN: { phcode: "599", countryName: "Антильские острова", key: "AN" },
	AO: { phcode: "244", countryName: "Ангола", key: "AO" },
	AQ: { phcode: "672", countryName: "Антарктика", key: "AQ" },
	AR: { phcode: "54", countryName: "Аргентина", key: "AR" },
	AS: { phcode: "1684", countryName: "Американские Самоа", key: "AS" },
	AT: { phcode: "43", countryName: "Австрия", key: "AT" },
	AU: { phcode: "61", countryName: "Австралия", key: "AU" },
	AW: { phcode: "297", countryName: "Аруба", key: "AW" },
	AX: { phcode: "3581", countryName: "Аландские острова", key: "AX" },
	AZ: { phcode: "994", countryName: "Азербайджан", key: "AZ" },
	BA: { phcode: "387", countryName: "Босния и Герцеговина", key: "BA" },
	BB: { phcode: "1246", countryName: "Барбадос", key: "BB" },
	BD: { phcode: "880", countryName: "Бангладеш", key: "BD" },
	BE: { phcode: "32", countryName: "Бельгия", key: "BE" },
	BF: { phcode: "226", countryName: "Буркина Фасо", key: "BF" },
	BG: { phcode: "359", countryName: "Болгария", key: "BG" },
	BH: { phcode: "973", countryName: "Бахрейн", key: "BH" },
	BI: { phcode: "257", countryName: "Бурунди", key: "BI" },
	BJ: { phcode: "229", countryName: "Бенин", key: "BJ" },
	BL: { phcode: "590", countryName: "Санкт-Бартельми", key: "BL" },
	BM: { phcode: "1441", countryName: "Бермуды", key: "BM" },
	BN: { phcode: "673", countryName: "Бруней-Даруссалам", key: "BN" },
	BO: { phcode: "591", countryName: "Боливия", key: "BO" },
	BR: { phcode: "55", countryName: "Бразилия", key: "BR" },
	BS: { phcode: "1242", countryName: "Багамы", key: "BS" },
	BT: { phcode: "975", countryName: "Бутан", key: "BT" },
	BV: { phcode: "47", countryName: "Буве", key: "BV" },
	BW: { phcode: "267", countryName: "Ботсвана", key: "BW" },
	BY: { phcode: "375", countryName: "Беларусь", key: "BY" },
	BZ: { phcode: "501", countryName: "Белиз", key: "BZ" },
	CA: { phcode: "1", countryName: "Канада", key: 'CA' },
	CC: { phcode: "61", countryName: "Кокосовые острова (Килинг)", key: "CC" },
	CD: { phcode: "242", countryName: "Демократическая Республика Конго", key: "CD" },
	CF: { phcode: "236", countryName: "Центрально-Африканская Республика", key: "CF" },
	CG: { phcode: "242", countryName: "Конго", key: "CG" },
	CH: { phcode: "41", countryName: "Швейцария", key: "CH" },
	CI: { phcode: "225", countryName: "Кот-д`Ивуар", key: "CI" },
	CK: { phcode: "682", countryName: "Острова Кука", key: "CK" },
	CL: { phcode: "56", countryName: "Чили", key: "CL" },
	CM: { phcode: "237", countryName: "Камерун", key: "CM" },
	CN: { phcode: "86", countryName: "Китай", key: "CN" },
	CO: { phcode: "57", countryName: "Колумбия", key: "CO" },
	CR: { phcode: "506", countryName: "Коста-Рика", key: "CR" },
	CU: { phcode: "53", countryName: "Куба", key: "CU" },
	CV: { phcode: "238", countryName: "Кабо-Верде", key: "CV" },
	CX: { phcode: "61", countryName: "Остров Рождества", key: "CX" },
	CY: { phcode: "357", countryName: "Кипр", key: "CY" },
	CZ: { phcode: "420", countryName: "Чешская Республика", key: "CZ" },
	DE: { phcode: "49", countryName: "Германия", key: "DE" },
	DJ: { phcode: "253", countryName: "Джибути", key: "DJ" },
	DK: { phcode: "45", countryName: "Дания", key: "DK" },
	DM: { phcode: "1767", countryName: "Доминикана", key: "DM" },
	DO: { phcode: "1809", countryName: "Доминиканская Республика", key: "DO" },
	DZ: { phcode: "213", countryName: "Алжир", key: "DZ" },
	EC: { phcode: "593", countryName: "Эквадор", key: "EC" },
	EE: { phcode: "372", countryName: "Эстония", key: "EE" },
	EG: { phcode: "20", countryName: "Египет", key: "EG" },
	EH: { phcode: "212", countryName: "Западная Сахара", key: "EH" },
	ER: { phcode: "291", countryName: "Эритрея", key: "ER" },
	ES: { phcode: "34", countryName: "Испания", key: "ES" },
	ET: { phcode: "251", countryName: "Эфиопия", key: "ET" },
	FI: { phcode: "358", countryName: "Финляндия", key: "FI" },
	FJ: { phcode: "679", countryName: "Фиджи", key: "FJ" },
	FK: { phcode: "500", countryName: "Фолклендские (Мальвинские) острова", key: "FK" },
	FM: { phcode: "691", countryName: "Микронезия", key: "FM" },
	FO: { phcode: "298", countryName: "Фарерские острова", key: "FO" },
	FR: { phcode: "33", countryName: "Франция", key: "FR" },
	GA: { phcode: "241", countryName: "Габон", key: "GA" },
	GB: { phcode: "44", countryName: "Великобритания", key: "GB" },
	GD: { phcode: "1473", countryName: "Гренада", key: "GD" },
	GE: { phcode: "995", countryName: "Грузия", key: "GE" },
	GF: { phcode: "594", countryName: "Французская Гвиана", key: "GF" },
	GG: { phcode: "4414", countryName: "Гернси", key: "GG" },
	GH: { phcode: "233", countryName: "Гана", key: "GH" },
	GI: { phcode: "350", countryName: "Гибралтар", key: "GI" },
	GL: { phcode: "299", countryName: "Гренландия", key: "GL" },
	GM: { phcode: "220", countryName: "Гамбия", key: "GM" },
	GN: { phcode: "224", countryName: "Гвинея", key: "GN" },
	GP: { phcode: "590", countryName: "Гваделупе", key: "GP" },
	GQ: { phcode: "240", countryName: "Экваториальная Гвинея", key: "GQ" },
	GR: { phcode: "30", countryName: "Греция", key: "GR" },
	GS: { phcode: "500", countryName: "Южная Джорджия и Южные Сандвичевы Острова", key: "GS" },
	GT: { phcode: "502", countryName: "Гватемале", key: "GT" },
	GU: { phcode: "1671", countryName: "Гуам", key: "GU" },
	GW: { phcode: "245", countryName: "Гвинея-Биссау", key: "GW" },
	GY: { phcode: "592", countryName: "Гайана", key: "GY" },
	HK: { phcode: "852", countryName: "Гонконг", key: "HK" },
	HM: { phcode: "672", countryName: "Острова Херд и Макдональд", key: "HM" },
	HN: { phcode: "504", countryName: "Гондурас", key: "HN" },
	HR: { phcode: "385", countryName: "Хорватия", key: "HR" },
	HT: { phcode: "509", countryName: "Гаити", key: "HT" },
	HU: { phcode: "36", countryName: "Венгрия", key: "HU" },
	ID: { phcode: "62", countryName: "Индонезия", key: "ID" },
	IE: { phcode: "353", countryName: "Ирландия", key: "IE" },
	IL: { phcode: "972", countryName: "Израиль", key: 'IL' },
	IM: { phcode: "44", countryName: "Остров Мэн", key: "IM" },
	IN: { phcode: "91", countryName: "Индия", key: "IN" },
	IO: { phcode: "246", countryName: "Британская территория в Индийском океане", key: "IO" },
	IQ: { phcode: "964", countryName: "Ирак", key: "IQ" },
	IR: { phcode: "98", countryName: "Иран", key: "IR" },
	IS: { phcode: "354", countryName: "Исландия", key: "IS" },
	IT: { phcode: "39", countryName: "Италия", key: "IT" },
	JE: { phcode: "4415", countryName: "Джерси", key: "JE" },
	JM: { phcode: "1876", countryName: "Ямайка", key: "JM" },
	JO: { phcode: "962", countryName: "Иордания", key: "JO" },
	JP: { phcode: "81", countryName: "Япония", key: "JP" },
	KE: { phcode: "254", countryName: "Кения", key: "KE" },
	KG: { phcode: "996", countryName: "Киргизстан", key: "KG" },
	KH: { phcode: "855", countryName: "Камбоджа", key: "KH" },
	KI: { phcode: "686", countryName: "Кирибати", key: "KI" },
	KM: { phcode: "269", countryName: "Коморские Острова", key: "KM" },
	KN: { phcode: "1758", countryName: "Сент-Китс и Невис", key: "KN" },
	KP: { phcode: "850", countryName: "Северная Корея", key: "KP" },
	KR: { phcode: "82", countryName: "Южная Корея", key: "KR" },
	KV: { phcode: "383", countryName: "Косово", key: 'KV' },
	KW: { phcode: "965", countryName: "Кувейт", key: "KW" },
	KY: { phcode: "1345", countryName: "Каймановы острова", key: "KY" },
	KZ: { phcode: "7", countryName: "Казахстан", key: "KZ" },
	LA: { phcode: "856", countryName: "Лаос", key: "LA" },
	LB: { phcode: "961", countryName: "Ливан", key: "LB" },
	LC: { phcode: "1758", countryName: "Сент-Люсии", key: "LC" },
	LI: { phcode: "423", countryName: "Лихтенштейн", key: "LI" },
	LK: { phcode: "94", countryName: "Шри-Ланка", key: "LK" },
	LR: { phcode: "231", countryName: "Либерия", key: "LR" },
	LS: { phcode: "266", countryName: "Лесото", key: "LS" },
	LT: { phcode: "370", countryName: "Литва", key: "LT" },
	LU: { phcode: "352", countryName: "Люксембург", key: "LU" },
	LV: { phcode: "371", countryName: "Латвия", key: "LV" },
	LY: { phcode: "218", countryName: "Ливия", key: "LY" },
	MA: { phcode: "212", countryName: "Морокко", key: "MA" },
	MC: { phcode: "377", countryName: "Монако", key: "MC" },
	MD: { phcode: "373", countryName: "Молдова", key: "MD" },
	ME: { phcode: "382", countryName: "Черногория", key: "ME" },
	MF: { phcode: "590", countryName: "Святой Мартин", key: "MF" },
	MG: { phcode: "261", countryName: "Мадагаскар", key: "MG" },
	MH: { phcode: "692", countryName: "Маршалловы Острова", key: "MH" },
	MK: { phcode: "389", countryName: "Македония", key: "MK" },
	ML: { phcode: "223", countryName: "Мали", key: "ML" },
	MM: { phcode: "95", countryName: "Мьянма", key: "MM" },
	MN: { phcode: "976", countryName: "Монголия", key: "MN" },
	MO: { phcode: "853", countryName: "Макао", key: "MO" },
	MP: { phcode: "1670", countryName: "Северные Марианские острова", key: "MP" },
	MQ: { phcode: "596", countryName: "Мартиника", key: "MQ" },
	MR: { phcode: "222", countryName: "Мавритания", key: "MR" },
	MS: { phcode: "1664", countryName: "Монтсеррат", key: "MS" },
	MT: { phcode: "356", countryName: "Мальта", key: "MT" },
	MU: { phcode: "230", countryName: "Остров Маврикий", key: "MU" },
	MV: { phcode: "960", countryName: "Мальдивы", key: "MV" },
	MW: { phcode: "265", countryName: "Малави", key: "MW" },
	MX: { phcode: "52", countryName: "Мексика", key: "MX" },
	MY: { phcode: "60", countryName: "Малайзия", key: "MY" },
	MZ: { phcode: "258", countryName: "Мозамбик", key: "MZ" },
	NA: { phcode: "264", countryName: "Намибия", key: "NA" },
	NC: { phcode: "687", countryName: "Новая Каледония", key: "NC" },
	NE: { phcode: "227", countryName: "Нигер", key: "NE" },
	NF: { phcode: "672", countryName: "Остров Норфолк", key: "NF" },
	NG: { phcode: "234", countryName: "Нигерия", key: "NG" },
	NI: { phcode: "505", countryName: "Никарагуа", key: "NI" },
	NL: { phcode: "31", countryName: "Нидерланды", key: "NL" },
	NO: { phcode: "47", countryName: "Норвегия", key: "NO" },
	NP: { phcode: "977", countryName: "Непал", key: "NP" },
	NR: { phcode: "674", countryName: "Науру", key: "NR" },
	NU: { phcode: "683", countryName: "Ниуэ", key: "NU" },
	NZ: { phcode: "64", countryName: "Новая Зеландия", key: "NZ" },
	OM: { phcode: "968", countryName: "Оман", key: "OM" },
	PA: { phcode: "507", countryName: "Панама", key: "PA" },
	PE: { phcode: "51", countryName: "Перу", key: "PE" },
	PF: { phcode: "689", countryName: "Французская Полинезия", key: "PF" },
	PG: { phcode: "675", countryName: "Папуа Новая Гвинея", key: "PG" },
	PH: { phcode: "63", countryName: "Филиппины", key: "PH" },
	PK: { phcode: "92", countryName: "Пакистан", key: "PK" },
	PL: { phcode: "48", countryName: "Польша", key: "PL" },
	PM: { phcode: "508", countryName: "Сен-Пьер и Микелон", key: "PM" },
	PN: { phcode: "64", countryName: "Питкэрн", key: "PN" },
	PR: { phcode: "1787", countryName: "Пуэрто-Рико", key: "PR" },
	PS: { phcode: "970", countryName: "Палестина", key: "PS" },
	PT: { phcode: "351", countryName: "Португалия", key: "PT" },
	PW: { phcode: "680", countryName: "Палау", key: "PW" },
	PY: { phcode: "595", countryName: "Парагвай", key: "PY" },
	QA: { phcode: "974", countryName: "Катар", key: "QA" },
	RE: { phcode: "262", countryName: "Реюньон", key: "RE" },
	RO: { phcode: "40", countryName: "Румыния", key: "RO" },
	RS: { phcode: "381", countryName: "Сербия", key: "RS" },
	RU: { phcode: "7", countryName: "Российская Федерация", key: "RU" },
	RW: { phcode: "250", countryName: "Руанда", key: "RW" },
	SA: { phcode: "966", countryName: "Саудовская Аравия", key: "SA" },
	SB: { phcode: "677", countryName: "Соломоновы острова", key: "SB" },
	SC: { phcode: "248", countryName: "Сейшеллы", key: "SC" },
	SD: { phcode: "249", countryName: "Судан", key: "SD" },
	SE: { phcode: "46", countryName: "Швеция", key: "SE" },
	SG: { phcode: "65", countryName: "Сингапур", key: "SG" },
	SH: { phcode: "290", countryName: "Святая Елена", key: "SH" },
	SI: { phcode: "386", countryName: "Словения", key: "SI" },
	SJ: { phcode: "47", countryName: "Свалбард и Жан Майен", key: "SJ" },
	SK: { phcode: "421", countryName: "Словакия", key: "SK" },
	SL: { phcode: "232", countryName: "Сьерра Лион", key: "SL" },
	SM: { phcode: "378", countryName: "Сан-Марино", key: "SM" },
	SN: { phcode: "221", countryName: "Сенегал", key: "SN" },
	SO: { phcode: "252", countryName: "Сомали", key: "SO" },
	SR: { phcode: "597", countryName: "Суринам", key: "SR" },
	SS: { phcode: "211", countryName: "Южный Судан", key: "SS" },
	ST: { phcode: "239", countryName: "Сан-Томе и Принсипи", key: "ST" },
	SV: { phcode: "503", countryName: "Сальвадор", key: "SV" },
	SY: { phcode: "963", countryName: "Сирия", key: "SY" },
	SZ: { phcode: "268", countryName: "Свазиленд", key: "SZ" },
	TC: { phcode: "1649", countryName: "Теркс и Кайкос", key: "TC" },
	TD: { phcode: "235", countryName: "Чад", key: "TD" },
	TF: { phcode: "689", countryName: "Французские Южные территории", key: "TF" },
	TG: { phcode: "228", countryName: "Того", key: "TG" },
	TH: { phcode: "66", countryName: "Таиланд", key: "TH" },
	TJ: { phcode: "992", countryName: "Таджикистан", key: "TJ" },
	TK: { phcode: "690", countryName: "Токелау", key: "TK" },
	TL: { phcode: "670", countryName: "Тимор-Лешти", key: "TL" },
	TM: { phcode: "993", countryName: "Туркменистан", key: "TM" },
	TN: { phcode: "216", countryName: "Тунис", key: "TN" },
	TO: { phcode: "676", countryName: "Тонга", key: "TO" },
	TP: { phcode: "670", countryName: "Восточный Тимор", key: 'TP' },
	TR: { phcode: "90", countryName: "Турция", key: "TR" },
	TT: { phcode: "1868", countryName: "Тринидад и Тобаго", key: "TT" },
	TV: { phcode: "688", countryName: "Тувалу", key: "TV" },
	TW: { phcode: "886", countryName: "Тайвань", key: "TW" },
	TZ: { phcode: "255", countryName: "Танзания", key: "TZ" },
	UA: { phcode: "380", countryName: "Украина", key: "UA" },
	UG: { phcode: "256", countryName: "Уганда", key: "UG" },
	UM: { phcode: "699", countryName: "США Внешние малые острова", key: "UM" },
	US: { phcode: "1", countryName: "США", key: "US" },
	UY: { phcode: "598", countryName: "Уругвай", key: "UY" },
	UZ: { phcode: "998", countryName: "Узбекистан", key: "UZ" },
	VA: { phcode: "379", countryName: "Ватикан", key: "VA" },
	VC: { phcode: "1784", countryName: "Сент-Винсент и Гренадины", key: "VC" },
	VE: { phcode: "58", countryName: "Венесуэла", key: "VE" },
	VG: { phcode: "1284", countryName: "Британские Виргинские острова", key: "VG" },
	VI: { phcode: "1340", countryName: "Американские Виргинские острова", key: "VI" },
	VN: { phcode: "84", countryName: "Вьетнам", key: "VN" },
	VU: { phcode: "678", countryName: "Вануату", key: "VU" },
	WF: { phcode: "681", countryName: "Уоллис и Футуна", key: "WF" },
	WS: { phcode: "685", countryName: "Самоа", key: "WS" },
	YE: { phcode: "967", countryName: "Йемен", key: "YE" },
	YT: { phcode: "262", countryName: "Майотта", key: "YT" },
	ZA: { phcode: "27", countryName: "Южная Африка", key: "ZA" },
	ZM: { phcode: "260", countryName: "Замбия", key: "ZM" },
	ZW: { phcode: "263", countryName: "Зимбабве", key: "ZW" }
};